### ISSUE TITLE
Error when uploading

### ISSUE THREAD

**Issue by deaddred** [backdrop-contrib/plupload#3]
I'm trying out the blulk media upload module and keep getting this error 

REFERRER http://bluei.ca/admin/content/file/bulk_upload 

Recoverable fatal error: Argument 1 passed to file_validate() must be an instance of File, instance of stdClass given, called in /home/***/public_html/modules/plupload/plupload/plupload.module on line 242 and defined in file_validate() (line 1654 of /home/***/public_html/core/includes/file.inc).

This is using the plupload version that is linked on the Backdrop CMS module page

**Comment by b3marketing** [comment]
Same issues:

Recoverable fatal error: Argument 1 passed to file_validate() must be an instance of File, instance of stdClass given, called in /code/modules/plupload/plupload.module on line 242 and defined in file_validate() (line 1648 of /code/core/includes/file.inc).
--

Trying to upload 7-8 images each under 1mb. Same error with a single image.

**Comment by Graham-72** [comment]
The bug here in plupload is fixed with PR #5. The issue in the bulk_media_upload module is in the process of being fixed.

**Comment by argiepiano** [comment]
This PR was merged a few years ago and is already part of version 1.7.3. Closing.
