### ISSUE TITLE
Consider including library in module

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/plupload#4]
The plupload library is GPL 3 so it should be fine to include it in this library to make it easier for beginners to install. https://github.com/moxiecode/plupload/blob/master/license.txt

Though you'd need to add a condition that it ignore the external library if it's included, for those who already installed it.

**Comment by Graham-72** [comment]
PR to do this: https://github.com/backdrop-contrib/plupload/pull/6

**Comment by argiepiano** [comment]
This PR was merged and is part of the latest release. Closing.
