### ISSUE TITLE
Assign temporary:// as default for config temporary_uri upon D7 upgrade

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/plupload#9]
`temporary_uri` is correctly assigned `temporary://` in the file `plupload.settings.json`. The issue is that, when you upgrade from D7, that config file is not installed. Instead, `plupload_update_1000()` assigns an empty string to it, causing issues when using plupload in upgraded sites.

**Comment by argiepiano** [comment]
PR #10 provided.

@backdrop-contrib/bug-squad : this module has no maintainer. Can someone please review and merge this PR, and do a new release?

**Comment by herbdool** [comment]
Fixed
